import { AlertOctagon, AlertTriangle } from "lucide-react";
import { formatMetric, formatPeriodShort, humanize, isMonthlyMetric, METRIC_GROUPS, METRICS, metricLabel, resolveBindings, tidyTitle } from "../lib/format";
import type { Benchmarks, Finding, HealthScore, Metric } from "../lib/types";
import { Sparkline } from "./ui";

// Statement figures lead; for a bank-statement-only analysis the cash figures fill the strip instead.
const HEADLINE = ["ebitda", "net_profit_margin", "current_ratio", "debt_to_equity", "revenue_growth_yoy", "dso",
  "bank_closing_balance", "bank_avg_monthly_inflow", "bank_cash_cover_months", "bank_top_payer_share"];

/** metric_code -> [{period, value}] ascending by period */
export function seriesByMetric(metrics: Metric[]) {
  const map = new Map<string, { period: string; value: number | null; unit: string }[]>();
  for (const m of metrics) map.set(m.metric_code, [...(map.get(m.metric_code) ?? []), { period: m.period_end, value: m.value, unit: m.unit }]);
  for (const v of map.values()) v.sort((a, b) => a.period.localeCompare(b.period));
  return map;
}

export function direction(code: string, prev: number | null | undefined, cur: number | null | undefined): boolean | null {
  if (prev === null || prev === undefined || cur === null || cur === undefined || prev === cur) return null;
  const up = cur > prev;
  return METRICS[code]?.higherIsBetter === false ? !up : up;
}

export function changeText(unit: string, prev: number, cur: number): string {
  const d = cur - prev;
  if (d === 0) return "No change";
  if ((unit === "days" && Math.round(d) === 0) || (unit === "%" && Math.abs(d * 100) < 0.05) || (unit === "x" && Math.abs(d) < 0.005)) return "No change";
  const sign = d > 0 ? "+" : "−";
  if (unit === "%") return `${sign}${Math.abs(d * 100).toFixed(1)} pts`;
  if (unit === "x") return `${sign}${Math.abs(d).toFixed(2)}×`;
  if (unit === "days") return `${sign}${Math.abs(Math.round(d))} days`;
  if (unit === "months") return `${sign}${Math.abs(d).toFixed(1)} months`;
  if (unit === "pts") return `${sign}${Math.abs(Math.round(d))} pts`;
  if (prev !== 0) return `${sign}${Math.abs((d / Math.abs(prev)) * 100).toFixed(1)}%`;
  return sign + formatMetric(Math.abs(d), unit);
}

export function HeadlineFigures({ metrics }: { metrics: Metric[] }) {
  const series = seriesByMetric(metrics);
  const codes = HEADLINE.filter((c) => series.get(c)?.some((p) => p.value !== null)).slice(0, 4);
  if (!codes.length) return null;
  return (
    <div className="headline">
      {codes.map((code) => {
        const s = series.get(code)!.filter((p) => p.value !== null);
        const cur = s[s.length - 1];
        const prev = s[s.length - 2];
        const good = direction(code, prev?.value, cur.value);
        return (
          <div key={code} className="headline-fig">
            <div className="headline-label">{metricLabel(code)}</div>
            <div className={`headline-value ${cur.unit === "INR" && (cur.value ?? 0) < 0 ? "neg" : ""}`}>{formatMetric(cur.value, cur.unit)}</div>
            <div className="headline-meta">
              <span>{formatPeriodShort(cur.period, isMonthlyMetric(code))}</span>
              {prev && good !== null && (
                <span className={good ? "delta-good" : "delta-bad"}>{changeText(cur.unit, prev.value!, cur.value!)} vs {formatPeriodShort(prev.period, isMonthlyMetric(code))}</span>
              )}
            </div>
          </div>
        );
      })}
    </div>
  );
}

const BANDS = [
  { label: "Poor", from: 0 }, { label: "Weak", from: 20 }, { label: "Moderate", from: 40 },
  { label: "Good", from: 60 }, { label: "Excellent", from: 80 },
];

export function HealthRating({ health }: { health: HealthScore }) {
  const included = health.breakdown.filter((b) => b.included);
  return (
    <section className="panel health">
      <div className="health-top">
        <div>
          <h2 className="panel-title">Financial health</h2>
          <p className="muted small">Rules-based score over five core ratios. Not generated by the model.</p>
        </div>
        <div className="health-score">
          <span className="health-num">{health.score}</span>
          <span className="health-of">/ 100</span>
          <span className="health-rating">{health.rating}</span>
        </div>
      </div>
      <div className="band" role="img" aria-label={`Score ${health.score} of 100, rated ${health.rating}`}>
        {BANDS.map((b) => (
          <div key={b.label} className={`band-seg ${health.rating === b.label ? "band-on" : ""}`}><span>{b.label}</span></div>
        ))}
        <div className="band-marker" style={{ left: `${Math.min(99.5, Math.max(0.5, health.score))}%` }} />
      </div>
      <dl className="health-breakdown">
        {health.breakdown.map((b) => (
          <div key={b.metric_code} className={b.included ? "" : "excluded"}>
            <dt>{metricLabel(b.metric_code)}</dt>
            <dd>
              <span className="pts-bar"><span style={{ width: `${(b.points / b.weight) * 100}%` }} /></span>
              <span className="pts">{b.included ? `${b.points}/${b.weight}` : "No data"}</span>
            </dd>
          </div>
        ))}
      </dl>
      {included.length < health.breakdown.length && (
        <p className="muted small">Missing ratios score zero, so the score understates health when statements are incomplete.</p>
      )}
    </section>
  );
}

export const isForecast = (code: string) => code.endsWith("_forecast");

export function MetricSpread({ metrics, maxPeriods = 4 }: { metrics: Metric[]; maxPeriods?: number }) {
  const series = seriesByMetric(metrics);
  const allPeriods = [...new Set(metrics.map((m) => m.period_end))].sort();
  const periods = allPeriods.slice(-maxPeriods);
  // Bank-statement tables are monthly: label "Mar 24", not "FY24".
  const monthly = [...series.keys()].every(isMonthlyMetric);
  const known = METRIC_GROUPS.map((g) => ({ group: g, codes: Object.keys(METRICS).filter((c) => METRICS[c].group === g && series.has(c)) }));
  const other = [...series.keys()].filter((c) => !METRICS[c]);
  if (other.length) known.push({ group: "Other" as never, codes: other });

  return (
    <div className="spread-wrap">
      <table className="spread">
        <thead>
          <tr>
            <th scope="col">Ratio</th>
            {periods.map((p) => <th key={p} scope="col" className="num">{formatPeriodShort(p, monthly)}</th>)}
            <th scope="col" className="num">Change</th>
            <th scope="col" className="trend-col"><span className="sr-only">Trend</span></th>
          </tr>
        </thead>
        {known.filter((g) => g.codes.length).map(({ group, codes }) => (
          <tbody key={group}>
            <tr className="spread-group"><th colSpan={periods.length + 3} scope="colgroup">{group}</th></tr>
            {codes.map((code) => {
              const s = series.get(code)!;
              const byPeriod = new Map(s.map((p) => [p.period, p]));
              const vals = s.filter((p) => p.value !== null);
              const cur = vals[vals.length - 1];
              const prev = vals[vals.length - 2];
              const good = direction(code, prev?.value, cur?.value);
              return (
                <tr key={code}>
                  <th scope="row" title={METRICS[code]?.hint}>{metricLabel(code)}</th>
                  {periods.map((p) => {
                    const v = byPeriod.get(p);
                    const neg = v && v.unit === "INR" && (v.value ?? 0) < 0;
                    return <td key={p} className={`num ${neg ? "neg" : ""}`}>{v ? formatMetric(v.value, v.unit) : <span className="muted">–</span>}</td>;
                  })}
                  <td className={`num ${good === null ? "muted" : good ? "delta-good" : "delta-bad"}`}>
                    {prev && cur ? changeText(cur.unit, prev.value!, cur.value!) : "–"}
                  </td>
                  <td className="trend-col"><Sparkline values={vals.map((v) => v.value!)} good={good} /></td>
                </tr>
              );
            })}
          </tbody>
        ))}
      </table>
    </div>
  );
}

const SEV_ORDER: Record<string, number> = { error: 0, warn: 1, info: 2 };
const MODULE_LABEL: Record<string, string> = {
  ratio_trend: "Ratios", cash_working_capital: "Working capital", forecast: "Forecast",
  risk_anomaly: "Risk", gst_compliance: "GST",
};

/** Items that need a decision lead, expanded; routine observations sit behind one disclosure. */
export function Findings({ findings, metrics }: { findings: Finding[]; metrics: Metric[] }) {
  const sorted = [...findings].sort((a, b) => (SEV_ORDER[a.severity] ?? 3) - (SEV_ORDER[b.severity] ?? 3));
  const attention = sorted.filter((f) => f.severity === "error" || f.severity === "warn");
  const notes = sorted.filter((f) => f.severity !== "error" && f.severity !== "warn");

  return (
    <section aria-labelledby="findings-title">
      <div className="section-head">
        <h2 className="panel-title" id="findings-title">What needs attention</h2>
        {attention.length > 0 && <span className="muted small">{attention.length} of {findings.length} findings</span>}
      </div>
      {attention.length ? (
        <ul className="findings">{attention.map((f) => <FindingRow key={f.id} f={f} metrics={metrics} />)}</ul>
      ) : (
        <p className="all-clear">Nothing was flagged for attention. The observations below are for context.</p>
      )}
      {notes.length > 0 && (
        <details className="notes" open={!attention.length}>
          <summary>{notes.length} other observation{notes.length === 1 ? "" : "s"}</summary>
          <ul className="notes-list">
            {notes.map((f) => (
              <li key={f.id}>
                <span className="note-title">{tidyTitle(resolveBindings(f.title, metrics))}</span>
                {f.body && <span className="note-body">{resolveBindings(f.body, metrics)}</span>}
              </li>
            ))}
          </ul>
        </details>
      )}
    </section>
  );
}

function FindingRow({ f, metrics }: { f: Finding; metrics: Metric[] }) {
  const Icon = f.severity === "error" ? AlertOctagon : AlertTriangle;
  return (
    <li className={`finding finding-${f.severity}`}>
      <Icon size={16} className="finding-icon" aria-hidden="true" />
      <div className="finding-body">
        <div className="finding-title">
          <span className="sr-only">{f.severity === "error" ? "Critical: " : "Watch: "}</span>
          {tidyTitle(resolveBindings(f.title, metrics))}
        </div>
        {f.body && <p>{resolveBindings(f.body, metrics)}</p>}
        <div className="finding-meta">
          <span>{MODULE_LABEL[f.module] ?? humanize(f.module)}</span>
          {f.severity === "error" && <span className="sev-critical">Critical</span>}
        </div>
      </div>
    </li>
  );
}

type Tone = "good" | "watch" | "bad";

/** The audit-opinion line at the top of the overview: one sentence a reader can act on,
 * then the specifics it rests on. Built only from computed results, never generated text. */
export function SummaryOpinion({ health, findings, benchmarks, metrics }: {
  health: HealthScore | undefined;
  findings: Finding[];
  benchmarks: Benchmarks | undefined;
  metrics: Metric[];
}) {
  const critical = findings.filter((f) => f.severity === "error");
  const watch = findings.filter((f) => f.severity === "warn");
  const weak = health && ["Weak", "Poor"].includes(health.rating);
  const partialHealth = health && health.breakdown.some((b) => !b.included);

  let tone: Tone = "good";
  let lead: string;
  if (critical.length) {
    tone = "bad";
    lead = `${critical.length === 1 ? "One critical issue needs" : `${critical.length} critical issues need`} review before relying on these figures.`;
  } else if (weak) {
    tone = "bad";
    lead = "The company is under financial strain.";
  } else {
    const base = !health ? "Cash position reviewed" : health.rating === "Moderate" ? "A mixed picture" : "In good financial shape";
    if (watch.length) tone = "watch";
    lead = watch.length ? `${base}, with ${watch.length === 1 ? "one thing" : `${watch.length} things`} to watch.` : `${base}. Nothing was flagged for attention.`;
  }

  const details: string[] = [];
  if (health) details.push(`Health scores ${health.score} out of 100 (${health.rating.toLowerCase()})${partialHealth ? ", from incomplete statements" : ""}.`);
  const top = [...critical, ...watch][0];
  if (top) details.push(`${critical.length ? "Most pressing" : "To watch"}: ${tidyTitle(resolveBindings(top.title, metrics)).replace(/\.$/, "")}.`);
  if (benchmarks?.items.length) {
    const better = benchmarks.items.filter((i) => i.verdict === "better").length;
    const worse = benchmarks.items.filter((i) => i.verdict === "worse").length;
    const n = benchmarks.items.length;
    details.push(`Against ${benchmarks.label.toLowerCase()} peers, ${better} of ${n} ratios are stronger and ${worse ? `${worse} weaker` : "none weaker"}.`);
  }

  return (
    <section className={`opinion opinion-${tone}`} aria-label="Summary">
      <p className="opinion-lead">{lead}</p>
      {details.length > 0 && <p className="opinion-detail">{details.join(" ")}</p>}
    </section>
  );
}
