"""Restricted Python execution for agent-written pandas/numpy snippets (design doc's
"code-over-data" principle, §6.2/§6.3 sandbox.run_python).

Honest limitation: this is crash/runaway protection (separate process, timeout, blocked
imports of os/subprocess/socket/shutil/sys), NOT container-level isolation (no gVisor/
Firecracker, no network egress block at the OS level). That's an acceptable trade-off here
because the code being run is generated by our own analysis agents against our own data
handles, not arbitrary code from an untrusted end user. Document text is still always
passed to agents as data, never executed, per the prompt-injection defense in §9.
"""
from __future__ import annotations

import ast
import json
import subprocess
import sys
import tempfile
from pathlib import Path

from app.tools.registry import tool

_BLOCKED_MODULES = {"os", "subprocess", "socket", "shutil", "sys", "pathlib", "ctypes"}
_BLOCKED_NAMES = {"open", "__import__", "eval", "exec", "input", "compile"}


class SandboxError(Exception):
    pass


def _check_ast(code: str) -> None:
    try:
        tree = ast.parse(code)
    except SyntaxError as exc:
        raise SandboxError(f"code does not parse: {exc}") from exc

    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                if alias.name.split(".")[0] in _BLOCKED_MODULES:
                    raise SandboxError(f"import of '{alias.name}' is not allowed in the sandbox")
        elif isinstance(node, ast.ImportFrom):
            if node.module and node.module.split(".")[0] in _BLOCKED_MODULES:
                raise SandboxError(f"import of '{node.module}' is not allowed in the sandbox")
        elif isinstance(node, ast.Name) and node.id in _BLOCKED_NAMES:
            raise SandboxError(f"use of '{node.id}' is not allowed in the sandbox")


_SCRIPT_TEMPLATE = """
import json
import pandas as pd
import numpy as np

with open({data_path!r}) as _f:
    _raw = json.load(_f)
DATA = {{k: pd.DataFrame(v) for k, v in _raw.items()}}
RESULT = None


def set_result(value):
    global RESULT
    RESULT = value


{user_code}

def _default(o):
    try:
        return float(o)
    except Exception:
        return str(o)


print("__RESULT_JSON_START__")
print(json.dumps(RESULT, default=_default))
print("__RESULT_JSON_END__")
"""


def run_python(code: str, dataframes: dict[str, list] | None = None, timeout_s: int = 15) -> dict:
    """Runs `code` in a subprocess with DATA={name: pandas.DataFrame(records)} in scope.
    The code should call set_result(value) with a JSON-serializable result."""
    _check_ast(code)
    dataframes = dataframes or {}

    with tempfile.TemporaryDirectory() as tmp:
        data_path = Path(tmp) / "data.json"
        data_path.write_text(json.dumps(dataframes))
        script_path = Path(tmp) / "script.py"
        script_path.write_text(_SCRIPT_TEMPLATE.format(data_path=str(data_path), user_code=code))

        try:
            proc = subprocess.run(
                [sys.executable, str(script_path)],
                capture_output=True, text=True, timeout=timeout_s,
            )
        except subprocess.TimeoutExpired as exc:
            raise SandboxError(f"sandbox execution timed out after {timeout_s}s") from exc

        if proc.returncode != 0:
            raise SandboxError(f"sandbox script failed:\n{proc.stderr[-2000:]}")

        stdout = proc.stdout
        result = None
        if "__RESULT_JSON_START__" in stdout:
            payload = stdout.split("__RESULT_JSON_START__", 1)[1].split("__RESULT_JSON_END__", 1)[0].strip()
            if payload and payload != "null":
                result = json.loads(payload)
        return {"stdout": stdout, "result": result}


tool("sandbox.run_python", allowed_agents=["cash_wc", "risk"], timeout_s=20)(run_python)
